### ISSUE TITLE
Your amazing code! 

### ISSUE THREAD

**Issue by melaniesigrid** [Nizamuddin4493/toDoList#1]
Nizam, you are doing a great job with your list structure! During out morning session, we noticed 2 changes we would like to suggest to you:

- Add information to your README file according to Microverse's template.
- Change the font of your template
- Add functionality to your template.

Cheers, and happy coding!

**Comment by Nizamuddin4493** [comment]
# Hi @melaniesigrid :hibiscus: 
### Thank you for your Acknowledgment of the Readme file. I update the Readme file, and I think the font is ok. We can read it. and some functionality was added.
#### Thanks once again for pointing such an important Issue. :+1:
